/**
 * pruebaloopback
 * pruebaloopback
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: fer.borgognoni@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvitadoWithRelations } from './invitadoWithRelations';
import { OpcionWithRelations } from './opcionWithRelations';


/**
 * (tsType: EventoWithRelations, schemaOptions: { includeRelations: true })
 */
export interface EventoWithRelations { 
    id?: string;
    nombre: string;
    descripcion?: string;
    password: string;
    usuarioCreadorID?: string;
    opciones?: Array<OpcionWithRelations>;
    invitados?: Array<InvitadoWithRelations>;
}

