/**
 * pruebaloopback
 * pruebaloopback
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: fer.borgognoni@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Partial<Invitado>, schemaOptions: { partial: true })
 */
export interface InvitadoPartial { 
    id?: string;
    nombre?: string;
    email?: string;
    creador?: boolean;
    eventoId?: string;
}

