/**
 * pruebaloopback
 * pruebaloopback
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: fer.borgognoni@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Omit<Evento, \'id\'>, schemaOptions: { title: \'NewEvento\', exclude: [ \'id\' ] })
 */
export interface NewEvento { 
    nombre: string;
    descripcion?: string;
    password: string;
    codigoResultados?: string;
    resultadosPublicos: boolean;
    soloUnaOpcion: boolean;
    activo: boolean;
    invitadosDinamicos: boolean;
    usuarioCreadorID?: string;
    fechaCreacion: string;
}

