/**
 * pruebaloopback
 * pruebaloopback
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: fer.borgognoni@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: @loopback/repository-json-schema#Optional<Omit<Invitado, \'id\'>, \'eventoId\'>, schemaOptions: { title: \'NewInvitadoInEvento\', exclude: [ \'id\' ], optional: [ \'eventoId\' ] })
 */
export interface NewInvitadoInEvento { 
    nombre: string;
    email?: string;
    creador: boolean;
    eventoId?: string;
}

