/**
 * pruebaloopback
 * pruebaloopback
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: fer.borgognoni@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: @loopback/repository-json-schema#Optional<Omit<OpcionElegida, \'id\'>, \'opcionId\'>, schemaOptions: { title: \'NewOpcionElegidaInOpcion\', exclude: [ \'id\' ], optional: [ \'opcionId\' ] })
 */
export interface NewOpcionElegidaInOpcion { 
    invitadoId?: string;
    opcionId?: string;
}

