export * from './eventoController.service';
import { EventoControllerService } from './eventoController.service';
export * from './eventoInvitadoController.service';
import { EventoInvitadoControllerService } from './eventoInvitadoController.service';
export * from './eventoOpcionController.service';
import { EventoOpcionControllerService } from './eventoOpcionController.service';
export * from './invitadoController.service';
import { InvitadoControllerService } from './invitadoController.service';
export * from './invitadoOpcionElegidaController.service';
import { InvitadoOpcionElegidaControllerService } from './invitadoOpcionElegidaController.service';
export * from './mercadopagoController.service';
import { MercadopagoControllerService } from './mercadopagoController.service';
export * from './opcionElegidaController.service';
import { OpcionElegidaControllerService } from './opcionElegidaController.service';
export * from './opcionOpcionElegidaController.service';
import { OpcionOpcionElegidaControllerService } from './opcionOpcionElegidaController.service';
export * from './pingController.service';
import { PingControllerService } from './pingController.service';
export * from './suscripcionController.service';
import { SuscripcionControllerService } from './suscripcionController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [EventoControllerService, EventoInvitadoControllerService, EventoOpcionControllerService, InvitadoControllerService, InvitadoOpcionElegidaControllerService, MercadopagoControllerService, OpcionElegidaControllerService, OpcionOpcionElegidaControllerService, PingControllerService, SuscripcionControllerService, UserControllerService];
