export * from './eventoController.service';
import { EventoControllerService } from './eventoController.service';
export * from './eventoInvitadoController.service';
import { EventoInvitadoControllerService } from './eventoInvitadoController.service';
export * from './eventoOpcionController.service';
import { EventoOpcionControllerService } from './eventoOpcionController.service';
export * from './invitadoController.service';
import { InvitadoControllerService } from './invitadoController.service';
export * from './invitadoOpcionController.service';
import { InvitadoOpcionControllerService } from './invitadoOpcionController.service';
export * from './invitadoOpcionElegidaController.service';
import { InvitadoOpcionElegidaControllerService } from './invitadoOpcionElegidaController.service';
export * from './opcionElegidaController.service';
import { OpcionElegidaControllerService } from './opcionElegidaController.service';
export * from './opcionOpcionElegidaController.service';
import { OpcionOpcionElegidaControllerService } from './opcionOpcionElegidaController.service';
export * from './pingController.service';
import { PingControllerService } from './pingController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [EventoControllerService, EventoInvitadoControllerService, EventoOpcionControllerService, InvitadoControllerService, InvitadoOpcionControllerService, InvitadoOpcionElegidaControllerService, OpcionElegidaControllerService, OpcionOpcionElegidaControllerService, PingControllerService, UserControllerService];
